# https://taskfile.dev

version: "3"

vars:
  GREETING: Hello, World!

tasks:
  default:
    desc: Say hello
    cmds:
      - echo "{{.GREETING}}"
    silent: true

  list-files:
    desc: List all files in the current directory
    cmds:
      - ls
